---
settings:
  name: StorageGRID 11.7
  search: storagegrid-enable,storagegrid-117
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID 11.7文档
    url: "/index.html"
  - title: 发行说明
    url: "/release-notes/index.html"
  - title: 入门
    entries:
    - section: primer
    - section: network
    - title: StorageGRID 快速入门
      url: "/primer/quick-start.html"
  - title: 安装和升级
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: 配置和管理
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: 使用 StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 监控和故障排除
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: 维护
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: 启用StorageGRID
    url: "/storagegrid-enable.html"
  - title: 其他版本
    url: "/earlier-versions.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
