---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change bucket consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 如果您使用的是S3租户、则可以更改对S3存储分段中的对象执行操作的一致性级别。 
---
= 更改存储分段的一致性级别
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是S3租户、则可以更改对S3存储分段中的对象执行操作的一致性级别。

.开始之前
* 您将使用登录到租户管理器 link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您属于具有的用户组 link:tenant-management-permissions.html["管理所有分段或root访问权限"]。这些权限将覆盖组或存储分段策略中的权限设置。


.关于此任务
一致性控制可以在对象的可用性与这些对象在不同存储节点和站点之间的一致性之间实现平衡。通常，您应该对存储分段使用 * 读 - 后 - 新 - 写 * 一致性级别。

如果*读后新写入*一致性级别不符合客户端应用程序的要求、则可以通过设置存储分段一致性级别或使用来更改一致性级别 `Consistency-Control` 标题。。 `Consistency-Control` 标题将覆盖存储分段一致性级别。


NOTE: 更改存储分段的一致性级别时，只会保证更改后载入的对象符合修订后的级别。

.步骤
. 从信息板中选择*查看存储分段*，或选择*存储(S3)*>*存储分段*。
. 从表中选择分段名称。
+
此时将显示存储分段详细信息页面。

. 从*存储分段选项*选项卡中，选择*一致性级别*可调项。
. 为此存储分段中的对象选择一个一致性级别。
+
** *全部*：提供最高级别的一致性。所有节点都会立即接收数据，否则请求将失败。
** *强-全局*：保证所有站点中所有客户端请求的写入后读一致性。
** *强站点*：保证站点内所有客户端请求的写入后读一致性。
** *读后新写入*(默认)：为新对象提供读后写入一致性、并最终为对象更新提供一致性。提供高可用性和数据保护保证。建议用于大多数情况。
** *可用*：为新对象和对象更新提供最终一致性。对于S3存储分段、请仅在需要时使用(例如、对于包含很少读取的日志值的存储分段、或者对于不存在的密钥执行HEAD或GET操作)。S3 FabricPool 存储分段不支持。


. 选择 * 保存更改 * 。

