---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 在创建租户组之前，请考虑要分配给该组的权限。租户管理权限用于确定用户可以使用租户管理器或租户管理 API 执行的任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。 
---
= 租户管理权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建租户组之前，请考虑要分配给该组的权限。租户管理权限用于确定用户可以使用租户管理器或租户管理 API 执行的任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。

要登录到租户管理器或使用租户管理 API ，用户必须属于至少具有一个权限的组。所有可以登录的用户均可执行以下任务：

* 查看信息板
* 更改自己的密码（适用于本地用户）


对于所有权限，组的访问模式设置将确定用户是否可以更改设置并执行操作，或者是否只能查看相关设置和功能。


NOTE: 如果用户属于多个组，并且任何组设置为只读，则用户将对所有选定设置和功能具有只读访问权限。

您可以为组分配以下权限。请注意， S3 租户和 Swift 租户具有不同的组权限。

[cols="1a,3a"]
|===
| 权限 | Description 


 a| 
root 访问权限
 a| 
提供对租户管理器和租户管理 API 的完全访问权限。

*注意：* Swift用户必须具有root访问权限才能登录到租户帐户。



 a| 
管理员
 a| 
仅限 Swift 租户。提供对此租户帐户的 Swift 容器和对象的完全访问权限

* 注： * Swift 用户必须具有 Swift 管理员权限才能使用 Swift REST API 执行任何操作。



 a| 
管理您自己的S3凭据
 a| 
允许用户创建和删除自己的 S3 访问密钥。没有此权限的用户看不到*storage (S3)*>*My S3 access keys*菜单选项。



 a| 
管理所有存储分段
 a| 
* S3 租户：允许用户使用租户管理器和租户管理 API 创建和删除 S3 存储分段，并管理租户帐户中所有 S3 存储分段的设置，而不管 S3 存储分段或组策略如何。
+
没有此权限的用户看不到“*存储桶*”菜单选项。

* Swift 租户：允许 Swift 用户使用租户管理 API 控制 Swift 容器的一致性级别。


*注意：*您只能从租户管理API为Swift组分配"管理所有存储分段"权限。您不能使用租户管理器将此权限分配给Swift组。



 a| 
管理端点
 a| 
允许用户使用租户管理器或租户管理API创建或编辑平台服务端点、这些端点用作StorageGRID 平台服务的目标。

没有此权限的用户看不到“*平台服务端点*”菜单选项。



 a| 
使用S3控制台管理对象
 a| 
与管理所有存储分段权限结合使用时、允许用户从存储分段页面访问体验S3控制台。具有此权限但不具有"管理所有存储分段"权限的用户仍可直接导航到体验S3控制台。

|===