---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: browser inactivity timeout, inactive users 
summary: 如果 Grid Manager 和租户管理器用户处于非活动状态的时间超过一段时间，您可以控制他们是否已注销。 
---
= 更改浏览器非活动超时
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 Grid Manager 和租户管理器用户处于非活动状态的时间超过一段时间，您可以控制他们是否已注销。

.开始之前
* 您将使用登录到网格管理器 link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您具有 root 访问权限。


.关于此任务
浏览器非活动超时默认为15分钟。如果用户的浏览器在此时间段内未处于活动状态、则该用户将被注销。

您可以根据需要通过设置*注销非活动用户*选项来增加或减少超时期限。

浏览器非活动超时还受以下因素控制：

* 一个单独的不可配置 StorageGRID 计时器，其中包括用于系统安全保护的计时器。默认情况下，每个用户的身份验证令牌在用户登录后 16 小时到期。当用户的身份验证过期时、即使禁用了浏览器非活动超时或尚未达到浏览器超时值、该用户也会自动注销。要续订令牌，用户必须重新登录。
* 身份提供程序的超时设置(假设为StorageGRID 启用了单点登录(SSO))。
+
如果启用了SSO且用户的浏览器超时、则用户必须重新输入其SSO凭据才能再次访问StorageGRID。请参见 link:configuring-sso.html["配置单点登录"]。



.步骤
. 选择*configuration*>*Security*>*Security settings。
. 选择*浏览器非活动超时*选项卡。
. 在*注销非活动用户后*字段中，指定浏览器超时期限，介于60秒到7天之间。
+
您可以指定浏览器超时期限(以秒、分钟、小时或天为单位)。

. 选择 * 保存 * 。如果浏览器在指定时间内处于非活动状态、则用户将从网格管理器或租户管理器中注销。
+
新设置不会影响当前已登录的用户。用户必须重新登录或刷新浏览器，新的超时设置才能生效。


