---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理节点可提供系统配置，监控和日志记录等管理服务。每个网格都必须有一个主管理节点，并且可能有任意数量的非主管理节点，以实现冗余。 
---
= 什么是管理节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理节点可提供系统配置，监控和日志记录等管理服务。每个网格都必须有一个主管理节点，并且可能有任意数量的非主管理节点，以实现冗余。

登录到网格管理器或租户管理器时，您正在连接到管理节点。您可以连接到任何管理节点，每个管理节点都会显示一个类似的 StorageGRID 系统视图。但是，必须使用主管理节点执行维护过程。

管理节点还可用于对 S3 和 Swift 客户端流量进行负载平衡。



== 首选发件人是什么

如果您的StorageGRID 部署包含多个管理节点、则主管理节点是警报通知、AutoSupport 消息、SNMP陷阱和通知以及原有警报通知的首选发送方。

在正常系统操作下、只有首选发送方会发送通知。但是、所有其他管理节点都会监控首选发件人。如果检测到问题、其他管理节点将充当_standby senders。

在以下情况下、可能会发送多个通知：

* 如果管理节点彼此"被拒"、则首选发件人和备用发件人都将尝试发送通知、并且可能会收到多个通知副本。
* 如果备用发件人检测到首选发件人的问题并开始发送通知、则首选发件人可能会重新获得发送通知的能力。如果发生这种情况，可能会发送重复的通知。当备用发件人不再检测到首选发件人的错误时，它将停止发送通知。
+

NOTE: 测试AutoSupport 消息时、所有管理节点都会发送测试电子邮件。在测试警报通知时，您必须登录到每个管理节点以验证连接。





== 管理节点的主服务

下表显示了管理节点的主服务；但是，此表并未列出所有节点服务。

[cols="1a,2a"]
|===
| 服务 | 关键功能 


 a| 
审核管理系统（ AMS ）
 a| 
跟踪系统活动和事件。



 a| 
配置管理节点（ CMN ）
 a| 
管理系统范围的配置。仅限主管理节点。



 a| 
管理应用程序程序接口（ mgmt-API ）
 a| 
处理来自网格管理 API 和租户管理 API 的请求。



 a| 
高可用性
 a| 
管理管理节点和网关节点组的高可用性虚拟 IP 地址。

* 注： * 此服务也可在网关节点上找到。



 a| 
负载平衡器
 a| 
为从客户端到存储节点的 S3 和 Swift 流量提供负载平衡。

* 注： * 此服务也可在网关节点上找到。



 a| 
网络管理系统（ NMS ）
 a| 
提供网格管理器的功能。



 a| 
Prometheus
 a| 
从所有节点上的服务收集和存储时间序列指标。



 a| 
服务器状态监控器（ SSM ）
 a| 
监控操作系统和底层硬件。

|===