---
permalink: admin/what-archive-node-is.html 
sidebar: sidebar 
keywords: archive node 
summary: 您也可以选择使用归档节点部署每个 StorageGRID 数据中心站点，以便连接到目标外部归档存储系统，例如 Tivoli Storage Manager （ TSM ）。 
---
= 什么是归档节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您也可以选择使用归档节点部署每个 StorageGRID 数据中心站点，以便连接到目标外部归档存储系统，例如 Tivoli Storage Manager （ TSM ）。

[CAUTION]
====
已弃用对归档节点的支持(使用S3 API归档到云以及使用TSM中间件归档到磁带)、并将在未来版本中删除。将对象从归档节点移动到外部归档存储系统已被提供更多功能的ILM云存储池所取代。

请参见

* link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["将对象迁移到云存储池"]
* link:../ilm/what-cloud-storage-pool-is.html["使用云存储池"]


此外、在StorageGRID 11.7或更早版本中、您应从活动ILM策略中删除归档节点。删除存储在归档节点上的对象数据将简化将来的升级。请参见 link:../ilm/working-with-ilm-rules-and-ilm-policies.html["使用ILM规则和ILM策略"]。

====
归档节点提供了一个接口，您可以通过该接口将外部归档存储系统作为长期存储对象数据的目标。归档节点还会监控此连接以及 StorageGRID 系统与目标外部归档存储系统之间的对象数据传输。

配置与外部目标的连接后，您可以配置归档节点以优化 TSM 性能，在 TSM 服务器容量接近或不可用时使归档节点脱机，以及配置复制和检索设置。您还可以为归档节点设置自定义警报。

无法删除但未定期访问的对象数据可以随时从存储节点的旋转磁盘移至外部归档存储、例如云或磁带。对象数据的这种归档是通过配置数据中心站点的归档节点以及配置 ILM 规则来实现的，在这些规则中，此归档节点被选为内容放置说明的 " 目标 " 。归档节点不会管理归档对象数据本身；这可通过外部归档设备实现。


NOTE: 对象元数据不会归档，但会保留在存储节点上。



== 什么是 ARC-Service

归档节点上的归档（ Archive ， ARC-） 服务提供了一个管理界面，您可以使用此界面来配置通过 TSM 中间件连接到外部归档存储（例如磁带）的连接。

它是一种可与外部归档存储系统交互的应用程序服务，用于为近线存储发送对象数据，并在客户端应用程序请求归档对象时执行检索。当客户端应用程序请求归档对象时，存储节点会从 ARC-Service 请求对象数据。ARC-Service 会向外部归档存储系统发出请求，该系统会检索请求的对象数据并将其发送到 ARC-Service 。此应用程序服务会验证对象数据并将其转发到存储节点，然后存储节点会将此对象返回到请求的客户端应用程序。

通过 TSM 中间件将对象数据归档到磁带的请求可以进行管理，以提高检索效率。可以对请求进行排序，以便按同一顺序请求按顺序存储在磁带上的对象。然后，请求将排队等待提交到存储设备。根据归档设备的不同，可以同时处理对不同卷上的对象的多个请求。
