---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: 您可以使用 S3 后对象还原请求还原存储在云存储池中的对象。 
---
= 后对象还原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 后对象还原请求还原存储在云存储池中的对象。



== 支持的请求类型

StorageGRID 仅支持后对象还原请求来还原对象。它不支持 `SELECT` 还原类型。选择返回请求 `XNotImplemented`。



== 版本控制

(可选)指定 `versionId` 还原受版本控制的存储分段中特定版本的对象。如果未指定 `versionId`、将还原对象的最新版本



== 对云存储池对象执行后对象还原的行为

如果某个对象存储在云存储池中（请参见有关通过信息生命周期管理管理来管理对象的说明），则根据对象的状态，后对象还原请求具有以下行为。有关详细信息，请参见 "`head Object` " 。


NOTE: 如果某个对象存储在云存储池中，并且该对象的一个或多个副本也位于网格中，则无需发出后对象还原请求来还原该对象。相反，可以使用 GET 对象请求直接检索本地副本。

[cols="1a,2a"]
|===
| 对象的状态 | POST 对象还原的行为 


 a| 
对象已载入 StorageGRID ，但尚未通过 ILM 进行评估，或者对象不在云存储池中
 a| 
`403 Forbidden`， `InvalidObjectState`



 a| 
云存储池中的对象，但尚未过渡到无法检索的状态
 a| 
`200 OK` 不会进行任何更改。

*注意*：在将对象转换为不可检索状态之前，您不能更改它 `expiry-date`。



 a| 
对象已过渡到无法检索的状态
 a| 
`202 Accepted` 在请求正文中指定的天数内将对象的可检索副本还原到云存储池。在此期间结束时，对象将返回到无法检索的状态。

或者、也可以使用 `Tier` 请求元素以确定还原作业完成所需的时间 (`Expedited`， `Standard`或 `Bulk`）。如果未指定 `Tier`， `Standard` 已使用层。

*重要*：如果对象已迁移到S3 Glaciereep Archive或云存储池使用Azure Blb存储、则无法使用还原它 `Expedited` 层。返回以下错误 `403 Forbidden`， `InvalidTier`： `Retrieval option is not supported by this storage class`。



 a| 
正在从不可检索状态还原的对象
 a| 
`409 Conflict`， `RestoreAlreadyInProgress`



 a| 
对象已完全还原到云存储池
 a| 
`200 OK`

*注意：*如果对象已还原到可检索状态、则可以更改其 `expiry-date` 通过使用新值重新发出POST对象还原请求 `Days`。还原日期将相对于请求时间进行更新。

|===
.相关信息
link:../ilm/index.html["使用 ILM 管理对象"]

link:head-object.html["HEAD 对象"]

link:s3-operations-tracked-in-audit-logs.html["在审核日志中跟踪 S3 操作"]
