---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: 如果您计划停用存储节点，则必须了解 StorageGRID 如何管理该节点上的对象数据和元数据。 
---
= 存储节点停用注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您计划停用存储节点，则必须了解 StorageGRID 如何管理该节点上的对象数据和元数据。

停用存储节点时，应遵循以下注意事项和限制：

* 系统必须始终包含足够的存储节点以满足操作要求，包括模块数转换仲裁和活动 ILM 策略。要满足此限制，您可能需要在扩展操作中添加新的存储节点，然后才能停用现有存储节点。
* 如果在停用存储节点时断开了该存储节点的连接，则系统必须使用已连接存储节点中的数据重建数据，这可能会导致数据丢失。
* 删除存储节点时，必须通过网络传输大量对象数据。尽管这些传输不应影响正常系统操作，但它们可能会影响 StorageGRID 系统占用的网络带宽总量。
* 与正常系统操作相关的任务相比，与存储节点停用相关的任务的优先级更低。这意味着停用不会干扰 StorageGRID 系统的正常运行，也不需要计划系统在一段时间内处于非活动状态。由于停用是在后台执行的，因此很难估计完成此过程需要多长时间。通常，在系统处于静默状态或一次仅删除一个存储节点时，停用速度会更快。
* 停用存储节点可能需要数天或数周时间。相应地规划此操作步骤 。尽管停用过程不会影响系统运行，但它会限制其他过程。通常，在删除网格节点之前，您应执行任何计划内的系统升级或扩展。
* 涉及存储节点的停用过程可以在某些阶段暂停，以便在需要时运行其他维护过程，并在完成后继续执行。
* 正在运行停用任务时、无法在任何网格节点上运行数据修复操作。
* 在停用存储节点期间，不应对 ILM 策略进行任何更改。
* 删除存储节点时，节点上的数据将迁移到其他网格节点；但是，此数据不会从已停用的网格节点中完全删除。要永久安全地删除数据，必须在停用操作步骤 完成后擦除已停用网格节点的驱动器。
* 停用存储节点时，可能会发出以下警报，您可能会收到相关电子邮件和 SNMP 通知：
+
** * 无法与节点 * 警报通信。停用包含此 ADC-Service 的存储节点时会触发此警报。停用操作完成后，此警报将得到解决。
** VSTU （对象验证状态）警报。此通知级别的警报表示存储节点在停用过程中将进入维护模式。
** CASA （数据存储状态）警报。此主要级别的警报表示 Cassandra 数据库正在关闭，因为服务已停止。




.相关信息
link:restoring-object-data-to-storage-volume.html["将对象数据还原到存储卷"]
