---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 添加存储节点后、您可以使用EC重新平衡操作步骤 在现有存储节点和新存储节点之间重新分布经过纠删编码的片段。 
---
= 添加存储节点后重新平衡经过纠删编码的数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
添加存储节点后、您可以使用EC重新平衡操作步骤 在现有存储节点和新存储节点之间重新分布经过纠删编码的片段。

.开始之前
* 您已完成添加新存储节点的扩展步骤。
* 您已查看 link:considerations-for-rebalancing-erasure-coded-data.html["重新平衡经过纠删编码的数据的注意事项"]。
* 您了解此操作步骤 不会移动复制的对象数据，并且在确定将纠删编码的数据移动到何处时， EC 重新平衡操作步骤 不会考虑每个存储节点上的复制数据使用情况。
* 您拥有 `Passwords.txt` 文件


.此操作步骤 运行时会发生什么情况
启动操作步骤 之前、请注意以下事项：

* 如果一个或多个卷脱机(卸载)或联机(挂载)但处于错误状态、EC重新平衡操作步骤 将不会启动。
* EC 重新平衡操作步骤 会临时预留大量存储。可能会触发存储警报，但会在重新平衡完成后解决。如果没有足够的存储空间用于预留， EC 重新平衡操作步骤 将失败。无论操作步骤 出现故障还是成功， EC 重新平衡操作步骤 完成后都会释放存储预留。
* 如果在EC重新平衡过程中卷脱机或发生错误、则重新平衡过程将部分终止、而不会丢失任何数据。当所有卷均联机且无错误时、EC重新平衡操作步骤 可在其终止时恢复。
* 运行EC重新平衡操作步骤 时、ILM操作以及S3和Swift客户端操作的性能可能会受到影响。
+

NOTE: 如果需要超过 24 小时才能完成 EC 重新平衡操作步骤 期间用于上传对象（或对象部件）的 S3 和 Swift API 操作可能会失败。如果适用的ILM规则在加载时使用平衡放置或严格放置、则长时间放置操作将失败。此时将报告以下错误： `500 Internal Server Error`。



.步骤
. 【 Review object_storage]] 查看计划重新平衡的站点的当前对象存储详细信息。
+
.. 选择 * 节点 * 。
.. 选择站点上的第一个存储节点。
.. 选择 * 存储 * 选项卡。
.. 将光标置于"已用存储-对象数据"图表上方、可查看存储节点上当前复制的数据量和经过重复数据操作的数据。
.. 重复上述步骤以查看站点上的其他存储节点。


. 登录到主管理节点：
+
.. 输入以下命令： `ssh admin@_primary_Admin_Node_IP_`
.. 输入中列出的密码 `Passwords.txt` 文件
.. 输入以下命令切换到root： `su -`
.. 输入中列出的密码 `Passwords.txt` 文件
+
以root用户身份登录后、提示符将从变为 `$` to `#`。



. 启动操作步骤 ：
+
`rebalance-data start --site "_site-name_"`

+
适用于 `"_site-name_"`下、指定添加新存储节点的第一个站点。封闭 `site-name` 在报价中。

+
此时将启动 EC 重新平衡操作步骤 ，并返回作业 ID 。

. 复制作业 ID 。
. 监控 EC 重新平衡操作步骤 的状态。
+
** 要查看单个 EC 重新平衡操作步骤 的状态，请执行以下操作：
+
`rebalance-data status --job-id _job-id_`

+
适用于 `_job-id_`下、指定启动操作步骤 时返回的ID。

** 要查看当前 EC 重新平衡操作步骤 的状态以及先前完成的任何过程：
+
`rebalance-data status`

+
[NOTE]
====
要获取有关 rebalance-data 命令的帮助，请执行以下操作：

`rebalance-data --help`

====


. 根据返回的状态执行其他步骤：
+
** 状态为 `In progress`、EC重新平衡操作仍在运行。您应定期监控操作步骤 ，直到其完成。
+
要查看当前作业的估计完成时间和完成百分比：

+
... 选择 * 支持 * > * 工具 * > * 指标 * 。
... 在Grafana部分中选择*EC Overview*。
... 查看 * 网格 EC 作业预计完成时间 * 和 * 网格 EC 作业已完成百分比 * 信息板。


** 状态为 `Success`(可选) <<review_object_storage,查看对象存储>> 以查看此站点的更新详细信息。
+
现在，经过纠删编码的数据应在站点的存储节点之间更加平衡。

+
[TIP]
====
如果出现以下消息、请再次运行EC重新平衡操作步骤 、直到所有经过纠删编码的数据均已重新平衡为止：

`The moves in this rebalance job have been limited. To rebalance additional data, start EC rebalance again for the same site.`

====
** 状态为 `Failure`：
+
... 确认站点上的所有存储节点均已连接到网格。
... 检查并解决可能影响这些存储节点的任何警报。
... 重新启动EC重新平衡操作步骤 ：
+
`rebalance-data start –-job-id _job-id_`

... 如果EC重新平衡操作步骤 的状态仍为 `Failure`、请联系技术支持。




. 如果 EC 重新平衡操作步骤 生成的负载过多（例如，载入操作受到影响），请暂停操作步骤 。
+
`rebalance-data pause --job-id _job-id_`

. 如果您需要终止 EC 重新平衡操作步骤 （例如，以便执行 StorageGRID 软件升级），请输入以下内容：
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: 终止 EC 重新平衡操作步骤 后，已移动的所有数据片段都将保留在新位置。数据不会移回原始位置。

. 如果要在多个站点上使用纠删编码，请对所有其他受影响站点运行此操作步骤 。

